plugins {
    id 'com.android.application'
}

android {
    namespace 'com.autotune.arabic'
    compileSdk 35

    defaultConfig {
        applicationId 'com.autotune.arabic'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
